### ISSUE TITLE
Request: Add text in swipe action

### ISSUE THREAD

**Issue by Imaginous** [saket/swipe#11]
It would be nice if we could als add text next to an icon or instead of the icon.

Maybe we should be able to add another compose element.

**Comment by saket** [comment]
You can already do this by using `SwipeAction#icon`: 

https://github.com/saket/swipe/blob/8e91491938a9e11005fc9f37717e04a5d98d9013/swipe/src/main/kotlin/me/saket/swipe/SwipeAction.kt#L30
