### ISSUE TITLE
How to setup swipe to dismiss in one direction?

### ISSUE THREAD

**Issue by ColtonIdle** [saket/swipe#13]
Love using this! But not sure how to setup a swipe to dismiss in one direction, and a swipe for action in the other direction. anything specific I need to do or this lib not meant for that?

**Comment by saket** [comment]
Yea `swipe` wasn't designed with dismiss animations in mind, but can you try removing your item from its data-set when the dismiss action is performed?

**Comment by ColtonIdle** [comment]
Cool, wasn't sure if there was more to it. Cheers!

**Comment by saket** [comment]
Let me know how it goes! I won't mind adding an explicit removal animation in the future if the current experience isn't great.
