### ISSUE TITLE
Animation broken using compose 1.5.0-beta01

### ISSUE THREAD

**Issue by Schinizer** [saket/swipe#15]
### What broke?
When using compose `1.5.0-beta01`, `resetOffset()` animation will not complete.

<img width="540" alt="Screenshot 2023-06-05 at 11 52 41 PM" src="https://github.com/saket/swipe/assets/12343667/f7805a00-3bc5-4c7d-9857-428d92c20efb">

### How to reproduce?
Use compose `1.5.0-beta01`

### What made it broke?
Internally in compose's implementation, a `PointerInputResetException()` has been thrown causing cancellation.

### Potential fix?
Making `SwipeableActionsBox()` always enabled kinda fixes it. But I'm not sure if there are side effects.

**Comment by fitsuli** [comment]
I'd like to bring more attention to this issue, as it's still appearing with Compose `1.5.0-beta02`

**Comment by saket** [comment]
Fixed in [v1.2.0](https://github.com/saket/swipe/releases/tag/1.2.0). Thanks both of you!
