### ISSUE TITLE
[request] swipe up/down support ↕️

### ISSUE THREAD

**Issue by maceip** [saket/swipe#16]
First of all, what a great repo❗ :shipit: 

2) My compose-foo is weak:

I'm trying to copy the Gmail Android app account-switch on avatar-swipe-down animation (and subsequent view recycle).

IMHO it's one of the best UX elements on mobile - usable, fast, and beautiful!.

 Instagram just implemented something similar, but it's a avatar coin flip on tap  profile pic to what looks like a memoji.

I've searched far and wide on GitHub and this repo is the closest I've come to finding the promised land. I'm 📏🤏close to reverse engineering the Gmail APK. 

Any chance we can get up down swipe support on FABs?

Cc @saket @c5inco

Best,
Ryan 🌵

**Comment by maceip** [comment]
![20230706_072550](https://github.com/saket/swipe/assets/804368/26cd8607-9050-466d-a75a-fddbf716edf5)

**Comment by maceip** [comment]
![20230706_073456](https://github.com/saket/swipe/assets/804368/a8661998-27a0-4e81-9c3e-f35add741eee)

**Comment by saket** [comment]
Hey @maceip, `swipe` was designed for a very specific use-case -- horizontal swipe actions on list items. It can't handle arbitrary gestures for you. 

Have you tried using [Modifier.swipeable](https://developer.android.com/jetpack/compose/touch-input/pointer-input/drag-swipe-fling#swiping)?.
