### ISSUE TITLE
The ability to specify swiping directions

### ISSUE THREAD

**Issue by Abdulrahman-N** [saket/swipe#23]
Hello!

Currently, there is no way to specify swiping directions. This prevents me from using the library in some scenarios, such as having a horizontal pager with an item that has swiping capabilities.

**Comment by saket** [comment]
Is your pager only scrollable in one direction?

**Comment by Abdulrahman-N** [comment]
No, I'm using a horizontal pager/tab layout setup.

In the first tab, I have a list of items, and I want the items to be swipeable only in one direction.

**Comment by saket** [comment]
Gotcha. Let's merge this issue with https://github.com/saket/swipe/issues/17. Can you also try answering https://github.com/saket/swipe/issues/17#issuecomment-1730811014?

**Comment by Abdulrahman-N** [comment]
Sure! Thanks.
