### ISSUE TITLE
Support for content without background

### ISSUE THREAD

**Issue by alashow** [saket/swipe#4]
Currently, when content inside `SwipeableActionsBox` doesn't have any background or has translucent background color, `backgroundUntilSwipeThreshold` or swiped actions background is visible.

With `backgroundUntilSwipeThreshold=Color.Transparent` and content without background, it looks like this when swipe threshold is reached: 
<img width="523" alt="Screen Shot 2022-04-30 at 20 14 31" src="https://user-images.githubusercontent.com/5840013/166130697-82c6e053-bc75-4bdd-afd5-487cfd69ea33.png">

**Comment by saket** [comment]
Can you apply a solid background to your content?

**Comment by alashow** [comment]
No because I have screens with gradient background
|   |  |
| ------------- | ------------- |
| <img width="523" alt="Screen Shot 2022-04-30 at 21 09 41" src="https://user-images.githubusercontent.com/5840013/166131893-35460edd-3be8-4766-af0b-9a1ea9d11745.png">  | <img width="523" alt="Screen Shot 2022-04-30 at 21 11 18" src="https://user-images.githubusercontent.com/5840013/166131897-594fa8c0-a507-4680-8022-5ac5fd889d8a.png">

**Comment by saket** [comment]
Whoops! I should have only drawn the background behind the active swipe action instead of drawing it behind the entire content. Wanna help me out by sending a PR? Making this change would also remove the need to have `backgroundUntilSwipeThreshold`.

Great app btw!

**Comment by alashow** [comment]
> Great app btw!

Thanks!

I tried to implement this in #5. Decided to keep `backgroundUntilSwipeThreshold` because `onSwipe` doesn't get triggered until `swipeThreshold` so `backgroundUntilSwipeThreshold` can be used as UI indication of that.
