### ISSUE TITLE
Unintentional swipes while scrolling

### ISSUE THREAD

**Issue by alashow** [saket/swipe#8]
When using swipe actions on scrollable items, swipe actions gets triggered unintentionally.

It can be triggered more easily when list items have smaller heights.

https://user-images.githubusercontent.com/5840013/168461727-7986df7c-d956-4636-9622-53bc57e592f5.mp4

**Comment by saket** [comment]
Isn't this the default behavior of `Modifier.draggable`? Can `swipe` do something to protect against these unintentional swipes?

**Comment by alashow** [comment]
I guess nothing.. maybe it will improve with future `Modifier.draggable` improvements

**Comment by saket** [comment]
Opening this again for visibility.

**Comment by saket** [comment]
Filed an issue: https://issuetracker.google.com/u/1/issues/269627294
